# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

nums = [0, 1]

x = 1
while x < 4000000:
    nums.append(x)
    x = nums[-1] + nums[-2]

print(sum(( x if x % 2 == 0 else 0 for x in nums)))